import {
  SiArduino,
  SiBootstrap,
  SiC,
  SiCplusplus,
  SiCss,
  SiEspressif,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiPostman,
  SiPython,
  SiRaspberrypi,
  SiReact,
  SiSqlite,
  SiTailwindcss,
} from 'react-icons/si'
import { VscCode } from 'react-icons/vsc'
import {
  FiActivity,
  FiBox,
  FiCloud,
  FiCode,
  FiCpu,
  FiDatabase,
  FiGlobe,
  FiLayout,
  FiMonitor,
  FiRadio,
  FiSettings,
  FiTool,
} from 'react-icons/fi'

const techIconMap = {
  Python: SiPython,
  C: SiC,
  'C++': SiCplusplus,
  JavaScript: SiJavascript,
  SQL: FiDatabase,
  React: SiReact,
  HTML5: SiHtml5,
  CSS3: SiCss,
  Bootstrap: SiBootstrap,
  'Tailwind CSS': SiTailwindcss,
  Flask: SiFlask,
  'Node.js': SiNodedotjs,
  'Express.js': SiExpress,
  Express: SiExpress,
  'REST API': FiGlobe,
  'REST APIs': FiGlobe,
  Prisma: FiDatabase,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  Firebase: SiFirebase,
  SQLite: SiSqlite,
  'Siemens PLC': FiSettings,
  'Delta PLC': FiSettings,
  'Mitsubishi PLC': FiSettings,
  'Schneider PLC': FiSettings,
  SCADA: FiMonitor,
  HMI: FiLayout,
  Modbus: FiRadio,
  MQTT: FiRadio,
  'OPC-UA': FiCloud,
  ESP32: SiEspressif,
  Arduino: SiArduino,
  STM32: FiCpu,
  'Raspberry Pi': SiRaspberrypi,
  'Jetson Nano': FiCpu,
  'Sensors & Actuators': FiActivity,
  Git: SiGit,
  GitHub: SiGithub,
  'VS Code': VscCode,
  Postman: SiPostman,
  EasyEDA: FiTool,
  Proteus: FiBox,
  KiCad: FiTool,
  Figma: SiFigma,
  PLC: FiSettings,
}

export function getTechIcon(name) {
  return techIconMap[name] ?? FiCode
}
